baseURL = "/"
languageCode = "en-us"
title = "open letter to the open letter to the NixOS foundation"
theme = "hugo-journal"
enableGitInfo = false


[Author]
	name = "Nick Cao"

[Params]
	mainSections = [""]
	tagline = ""
	description = ""
